/**
 * The plugin shipped as a one-click example in the plugin manager.
 *
 * It is deliberately written the way a user would write one — plain JS against
 * the `athanor` global, no build step, no imports — and it covers three of the
 * four contribution kinds. The SQLite exporter is not a toy: `@dbml/core` has
 * no SQLite dialect at all, so this is the documented way to add a database
 * AthanorDB does not support out of the box.
 */
export const EXAMPLE_PLUGIN_NAME = "SQLite & naming toolkit";

export const EXAMPLE_PLUGIN_SOURCE = `athanor.plugin({
  id: "example.sqlite-toolkit",
  name: "SQLite & naming toolkit",
  version: "1.0.0",
  author: "AthanorDB example",
  description: "Adds a SQLite DDL exporter, a snake_case canvas command and a DBML table sorter.",
  settings: [
    { key: "ifNotExists", label: "Emit CREATE TABLE IF NOT EXISTS", type: "boolean", default: false },
    { key: "foreignKeys", label: "Emit PRAGMA foreign_keys", type: "boolean", default: true },
    {
      key: "identifierStyle",
      label: "Identifier quoting",
      type: "select",
      options: ["double-quotes", "backticks", "none"],
      default: "double-quotes",
    },
  ],
});

// --- helpers ---------------------------------------------------------------

function quoter(settings) {
  var style = (settings && settings.identifierStyle) || "double-quotes";
  return function (name) {
    var text = String(name);
    if (style === "none") return text;
    if (style === "backticks") return "\`" + text.replace(/\`/g, "\`\`") + "\`";
    return '"' + text.replace(/"/g, '""') + '"';
  };
}

function sqliteType(type) {
  var t = String(type || "").toLowerCase();
  if (/int/.test(t)) return "INTEGER";
  if (/char|clob|text|uuid|json|enum/.test(t)) return "TEXT";
  if (/blob|binary/.test(t)) return "BLOB";
  if (/real|float|double/.test(t)) return "REAL";
  if (/decimal|numeric|money/.test(t)) return "NUMERIC";
  if (/bool/.test(t)) return "INTEGER";
  if (/date|time/.test(t)) return "TEXT";
  return "TEXT";
}

function snake(name) {
  return String(name)
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[\\s-]+/g, "_")
    .replace(/__+/g, "_")
    .toLowerCase();
}

// --- exporter: SQLite DDL --------------------------------------------------

athanor.registerExporter({
  id: "sqlite",
  label: "SQL — SQLite",
  extension: "sql",
  description: "CREATE TABLE statements using SQLite storage classes.",
  run: function (project, context) {
    var settings = (context && context.settings) || {};
    var quote = quoter(settings);
    var createPrefix = settings.ifNotExists ? "CREATE TABLE IF NOT EXISTS " : "CREATE TABLE ";

    var tablesById = {};
    project.tables.forEach(function (t) {
      tablesById[t.id] = t;
    });

    var out = ["-- SQLite schema generated by the AthanorDB example plugin"];
    if (settings.foreignKeys !== false) out.push("PRAGMA foreign_keys = ON;");
    out.push("");

    project.tables.forEach(function (table) {
      var lines = [];
      var compositePk = (table.indexes || []).filter(function (i) {
        return i.pk;
      })[0];

      table.fields.forEach(function (field) {
        var parts = ["  " + quote(field.name) + " " + sqliteType(field.type)];
        if (field.pk && !compositePk) parts.push(field.increment ? "PRIMARY KEY AUTOINCREMENT" : "PRIMARY KEY");
        if (field.notNull && !field.pk) parts.push("NOT NULL");
        if (field.unique) parts.push("UNIQUE");
        if (field.default) parts.push("DEFAULT " + field.default);
        lines.push(parts.join(" "));
      });

      if (compositePk) {
        var pkCols = compositePk.fieldIds
          .map(function (id) {
            var f = table.fields.filter(function (x) {
              return x.id === id;
            })[0];
            return f ? quote(f.name) : null;
          })
          .filter(Boolean);
        if (pkCols.length) lines.push("  PRIMARY KEY (" + pkCols.join(", ") + ")");
      }

      project.refs.forEach(function (ref) {
        if (ref.from.tableId !== table.id) return;
        var target = tablesById[ref.to.tableId];
        if (!target) return;
        var fromField = table.fields.filter(function (f) {
          return f.id === ref.from.fieldId;
        })[0];
        var toField = target.fields.filter(function (f) {
          return f.id === ref.to.fieldId;
        })[0];
        if (!fromField || !toField) return;
        lines.push(
          "  FOREIGN KEY (" + quote(fromField.name) + ") REFERENCES " + quote(target.name) + "(" + quote(toField.name) + ")",
        );
      });

      out.push(createPrefix + quote(table.name) + " (");
      out.push(lines.join(",\\n"));
      out.push(");");

      (table.indexes || []).forEach(function (index, n) {
        if (index.pk) return;
        var cols = index.fieldIds
          .map(function (id) {
            var f = table.fields.filter(function (x) {
              return x.id === id;
            })[0];
            return f ? quote(f.name) : null;
          })
          .filter(Boolean);
        if (!cols.length) return;
        var name = index.name || table.name + "_idx_" + (n + 1);
        out.push(
          "CREATE " + (index.unique ? "UNIQUE " : "") + "INDEX " + quote(name) + " ON " + quote(table.name) + " (" + cols.join(", ") + ");",
        );
      });

      out.push("");
    });

    return out.join("\\n");
  },
});

// --- canvas command: rename everything to snake_case -----------------------

athanor.registerCanvasCommand({
  id: "snake-case-names",
  label: "Rename tables & columns to snake_case",
  description: "Applies snake_case to the selected tables, or to every table when nothing is selected.",
  shortcut: "Ctrl+Alt+K",
  run: function (project, context) {
    var selected = ((context && context.selection && context.selection.tableIds) || []);
    var scoped = selected.length > 0;
    var touched = 0;

    var tables = project.tables.map(function (table) {
      if (scoped && selected.indexOf(table.id) === -1) return table;
      touched++;
      return Object.assign({}, table, {
        name: snake(table.name),
        fields: table.fields.map(function (field) {
          return Object.assign({}, field, { name: snake(field.name) });
        }),
      });
    });

    return {
      project: Object.assign({}, project, { tables: tables }),
      message: "snake_case applied to " + touched + " table(s)",
    };
  },
});

// --- editor command: sort table blocks alphabetically ----------------------

athanor.registerEditorCommand({
  id: "sort-tables",
  label: "Sort table blocks alphabetically",
  description: "Reorders top-level Table blocks in the DBML buffer, leaving everything else in place.",
  shortcut: "Ctrl+Alt+T",
  run: function (input) {
    var lines = input.text.split("\\n");
    var blocks = [];
    var current = null;
    var depth = 0;

    lines.forEach(function (line) {
      if (!current) {
        var match = /^\\s*(Table|Enum|Ref|TableGroup|Project)\\b(.*)$/.exec(line);
        if (match) {
          current = { kind: match[1], name: (match[2].trim().split(/[\\s{]/)[0] || "").toLowerCase(), lines: [line] };
          depth = (line.match(/{/g) || []).length - (line.match(/}/g) || []).length;
          if (depth <= 0 && /}/.test(line)) {
            blocks.push(current);
            current = null;
          }
          return;
        }
        blocks.push({ kind: "other", name: "", lines: [line] });
        return;
      }
      current.lines.push(line);
      depth += (line.match(/{/g) || []).length - (line.match(/}/g) || []).length;
      if (depth <= 0) {
        blocks.push(current);
        current = null;
      }
    });
    if (current) blocks.push(current);

    var tables = blocks.filter(function (b) {
      return b.kind === "Table";
    });
    if (tables.length < 2) return { text: null, message: "Nothing to sort" };

    var sorted = tables.slice().sort(function (a, b) {
      return a.name.localeCompare(b.name);
    });
    var i = 0;
    var merged = blocks.map(function (b) {
      return b.kind === "Table" ? sorted[i++] : b;
    });

    return merged
      .map(function (b) {
        return b.lines.join("\\n");
      })
      .join("\\n");
  },
});
`;
