export interface CommunityTemplate {
  id: string;
  name: string;
  version: string;
  author: string;
  category: "export" | "import" | "canvas" | "editor" | "tools";
  description: string;
  icon: string;
  tags: string[];
  sourceCode: string;
}

export const COMMUNITY_TEMPLATES: CommunityTemplate[] = [
  {
    id: "template.sqlite-toolkit",
    name: "SQLite & Naming Toolkit",
    version: "1.0.0",
    author: "Communauté AthanorDB",
    category: "export",
    icon: "download",
    tags: ["sqlite", "sql", "snake_case", "toolkit", "export"],
    description:
      "Exporteur de DDL SQLite avec options de clés étrangères, commande de renommage snake_case et tri des tables.",
    sourceCode: `athanor.plugin({
  id: "community.sqlite-toolkit",
  name: "SQLite & Naming Toolkit",
  version: "1.0.0",
  author: "Communauté AthanorDB",
  description: "Exporte en DDL SQLite et fournit des utilitaires de nommage.",
  settings: [
    { key: "ifNotExists", label: "Émettre CREATE TABLE IF NOT EXISTS", type: "boolean", default: false },
    { key: "foreignKeys", label: "Activer PRAGMA foreign_keys", type: "boolean", default: true }
  ]
});

function sqliteType(type) {
  var t = String(type || "").toLowerCase();
  if (/int/.test(t)) return "INTEGER";
  if (/char|text|uuid|json/.test(t)) return "TEXT";
  if (/blob|binary/.test(t)) return "BLOB";
  if (/real|float|double/.test(t)) return "REAL";
  if (/bool/.test(t)) return "INTEGER";
  return "TEXT";
}

athanor.registerExporter({
  id: "sqlite-custom",
  label: "SQL — SQLite DDL",
  extension: "sql",
  description: "Génère les instructions CREATE TABLE adaptées à SQLite.",
  run: function (project, context) {
    var settings = (context && context.settings) || {};
    var prefix = settings.ifNotExists ? "CREATE TABLE IF NOT EXISTS " : "CREATE TABLE ";
    var out = ["-- SQLite DDL"];
    if (settings.foreignKeys !== false) out.push("PRAGMA foreign_keys = ON;\\n");

    project.tables.forEach(function (table) {
      var lines = [];
      table.fields.forEach(function (f) {
        var p = ["  \\"" + f.name + "\\" " + sqliteType(f.type)];
        if (f.pk) p.push(f.increment ? "PRIMARY KEY AUTOINCREMENT" : "PRIMARY KEY");
        if (f.notNull && !f.pk) p.push("NOT NULL");
        if (f.unique && !f.pk) p.push("UNIQUE");
        lines.push(p.join(" "));
      });
      out.push(prefix + "\\"" + table.name + "\\" (\\n" + lines.join(",\\n") + "\\n);\\n");
    });

    return out.join("\\n");
  }
});
`,
  },

  {
    id: "template.typescript-generator",
    name: "TypeScript Interfaces Generator",
    version: "1.1.0",
    author: "Communauté AthanorDB",
    category: "export",
    icon: "code",
    tags: ["typescript", "ts", "types", "interfaces", "frontend", "backend"],
    description: "Génère des interfaces et types TypeScript typés avec documentation JSDoc à partir de votre schéma.",
    sourceCode: `athanor.plugin({
  id: "community.typescript-generator",
  name: "TypeScript Interfaces Generator",
  version: "1.1.0",
  author: "Communauté AthanorDB",
  description: "Convertit les tables et énumérations en interfaces TypeScript.",
  settings: [
    { key: "useType", label: "Générer 'type' au lieu de 'interface'", type: "boolean", default: false },
    { key: "camelCase", label: "Convertir les champs en camelCase", type: "boolean", default: true }
  ]
});

function toPascal(str) {
  return String(str || "").replace(/(?:^|_|\\s)([a-z0-9])/g, function (_, l) { return l.toUpperCase(); });
}

function toCamel(str) {
  var p = toPascal(str);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

function tsType(type) {
  var t = String(type || "").toLowerCase();
  if (/int|serial|float|double|numeric|decimal|number/.test(t)) return "number";
  if (/bool/.test(t)) return "boolean";
  if (/char|text|uuid|string/.test(t)) return "string";
  if (/date|time|timestamp/.test(t)) return "Date";
  if (/json/.test(t)) return "Record<string, unknown>";
  return "string";
}

athanor.registerExporter({
  id: "ts-interfaces",
  label: "TypeScript — Interfaces & Types",
  extension: "ts",
  description: "Exporte toutes les tables en types TypeScript.",
  run: function (project, context) {
    var settings = (context && context.settings) || {};
    var isType = Boolean(settings.useType);
    var camel = settings.camelCase !== false;
    var out = ["/** TypeScript types generated by AthanorDB */\\n"];

    project.enums.forEach(function (e) {
      out.push("export type " + toPascal(e.name) + " =");
      var vals = e.values.map(function (v) { return "  | " + JSON.stringify(v.name); });
      out.push(vals.join("\\n") + ";\\n");
    });

    project.tables.forEach(function (t) {
      var name = toPascal(t.name);
      out.push(isType ? "export type " + name + " = {" : "export interface " + name + " {");
      t.fields.forEach(function (f) {
        var fname = camel ? toCamel(f.name) : f.name;
        var opt = !f.notNull && !f.pk ? "?" : "";
        out.push("  " + fname + opt + ": " + tsType(f.type) + ";");
      });
      out.push(isType ? "};\\n" : "}\\n");
    });

    return out.join("\\n");
  }
});
`,
  },

  {
    id: "template.prisma-exporter",
    name: "Prisma Schema Exporter",
    version: "1.0.0",
    author: "Communauté AthanorDB",
    category: "export",
    icon: "layers",
    tags: ["prisma", "orm", "nodejs", "database", "schema.prisma"],
    description: "Génère un fichier schema.prisma complet avec modèles, relations @relation, attributs @id et @unique.",
    sourceCode: `athanor.plugin({
  id: "community.prisma-exporter",
  name: "Prisma Schema Exporter",
  version: "1.0.0",
  author: "Communauté AthanorDB",
  description: "Exporte votre schéma AthanorDB au format Prisma ORM (schema.prisma).",
  settings: [
    { key: "provider", label: "Fournisseur de base de données", type: "select", options: ["postgresql", "mysql", "sqlite", "sqlserver"], default: "postgresql" }
  ]
});

function toPascal(str) {
  return String(str || "").replace(/(?:^|_|\\s)([a-z0-9])/g, function (_, l) { return l.toUpperCase(); });
}
function toCamel(str) {
  var p = toPascal(str);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

function pType(type) {
  var t = String(type || "").toLowerCase();
  if (/int|serial/.test(t)) return "Int";
  if (/bigint/.test(t)) return "BigInt";
  if (/bool/.test(t)) return "Boolean";
  if (/decimal|numeric|float/.test(t)) return "Float";
  if (/date|time|timestamp/.test(t)) return "DateTime";
  if (/json/.test(t)) return "Json";
  return "String";
}

athanor.registerExporter({
  id: "prisma-schema",
  label: "Prisma — schema.prisma",
  extension: "prisma",
  description: "Génère les modèles Prisma avec relations et contraintes.",
  run: function (project, context) {
    var provider = (context && context.settings && context.settings.provider) || "postgresql";
    var tablesById = {};
    project.tables.forEach(function (t) { tablesById[t.id] = t; });

    var out = [
      "// Prisma schema",
      'datasource db {',
      '  provider = "' + provider + '"',
      '  url      = env("DATABASE_URL")',
      '}',
      '',
      'generator client {',
      '  provider = "prisma-client-js"',
      '}',
      ''
    ];

    project.tables.forEach(function (t) {
      var modelName = toPascal(t.name);
      out.push("model " + modelName + " {");
      t.fields.forEach(function (f) {
        var fname = toCamel(f.name);
        var type = pType(f.type) + (!f.notNull && !f.pk ? "?" : "");
        var attrs = [];
        if (f.pk) attrs.push("@id" + (f.increment ? " @default(autoincrement())" : ""));
        if (f.unique && !f.pk) attrs.push("@unique");
        if (f.name !== fname) attrs.push('@map("' + f.name + '")');
        out.push("  " + fname.padEnd(16) + " " + type.padEnd(10) + (attrs.length ? " " + attrs.join(" ") : ""));
      });
      out.push("}\\n");
    });

    return out.join("\\n");
  }
});
`,
  },

  {
    id: "template.mermaid-erd",
    name: "Mermaid ER Diagram",
    version: "1.0.0",
    author: "Communauté AthanorDB",
    category: "export",
    icon: "frame",
    tags: ["mermaid", "erd", "markdown", "documentation", "diagram"],
    description: "Génère un diagramme Mermaid erDiagram pour documenter votre schéma dans GitHub ou Notion.",
    sourceCode: `athanor.plugin({
  id: "community.mermaid-erd",
  name: "Mermaid ER Diagram",
  version: "1.0.0",
  author: "Communauté AthanorDB",
  description: "Exporte le schéma en diagramme Mermaid erDiagram markdown."
});

athanor.registerExporter({
  id: "mermaid-er",
  label: "Mermaid — erDiagram",
  extension: "mmd",
  description: "Génère le diagramme relationnel Mermaid pour Markdown.",
  run: function (project) {
    var tablesById = {};
    project.tables.forEach(function (t) { tablesById[t.id] = t; });

    var out = ["erDiagram"];

    project.refs.forEach(function (ref) {
      var from = tablesById[ref.from.tableId];
      var to = tablesById[ref.to.tableId];
      if (from && to) {
        out.push("    " + from.name + " ||--o{ " + to.name + " : references");
      }
    });

    project.tables.forEach(function (t) {
      out.push("    " + t.name + " {");
      t.fields.forEach(function (f) {
        var key = f.pk ? " PK" : f.unique ? " UK" : "";
        out.push("        " + (f.type || "string") + " " + f.name + key);
      });
      out.push("    }");
    });

    return out.join("\\n");
  }
});
`,
  },

  {
    id: "template.graphql-sdl",
    name: "GraphQL Schema (SDL)",
    version: "1.0.0",
    author: "Communauté AthanorDB",
    category: "export",
    icon: "code",
    tags: ["graphql", "sdl", "api", "types"],
    description: "Génère la définition de types GraphQL (SDL) pour vos APIs.",
    sourceCode: `athanor.plugin({
  id: "community.graphql-sdl",
  name: "GraphQL Schema (SDL)",
  version: "1.0.0",
  author: "Communauté AthanorDB",
  description: "Convertit les tables de base de données en types d'objets GraphQL."
});

function toPascal(str) {
  return String(str || "").replace(/(?:^|_|\\s)([a-z0-9])/g, function (_, l) { return l.toUpperCase(); });
}

function gqlType(type) {
  var t = String(type || "").toLowerCase();
  if (/int|serial/.test(t)) return "Int";
  if (/float|double|decimal|numeric/.test(t)) return "Float";
  if (/bool/.test(t)) return "Boolean";
  if (/uuid/.test(t)) return "ID";
  return "String";
}

athanor.registerExporter({
  id: "graphql-types",
  label: "GraphQL — Schema SDL",
  extension: "graphql",
  description: "Génère les types GraphQL pour chaque table du schéma.",
  run: function (project) {
    var out = ["# GraphQL SDL generated by AthanorDB\\n"];
    project.tables.forEach(function (t) {
      out.push("type " + toPascal(t.name) + " {");
      t.fields.forEach(function (f) {
        var req = (f.notNull || f.pk) ? "!" : "";
        out.push("  " + f.name + ": " + gqlType(f.type) + req);
      });
      out.push("}\\n");
    });
    return out.join("\\n");
  }
});
`,
  },

  {
    id: "template.schema-linter",
    name: "Schema Quality Linter",
    version: "1.0.0",
    author: "Communauté AthanorDB",
    category: "tools",
    icon: "sparkles",
    tags: ["linter", "quality", "audit", "validation"],
    description:
      "Vérifie les conventions du schéma : clés primaires manquantes, tables sans relations et colonnes non typées.",
    sourceCode: `athanor.plugin({
  id: "community.schema-linter",
  name: "Schema Quality Linter",
  version: "1.0.0",
  author: "Communauté AthanorDB",
  description: "Analyse et vérifie la qualité globale du schéma relationnel."
});

athanor.registerCanvasCommand({
  id: "run-linter",
  label: "Auditer la qualité du schéma",
  description: "Vérifie les clés primaires et l'intégrité des tables.",
  shortcut: "Ctrl+Alt+L",
  run: function (project) {
    var warnings = [];
    var referenced = {};
    project.refs.forEach(function (r) {
      referenced[r.from.tableId] = true;
      referenced[r.to.tableId] = true;
    });

    project.tables.forEach(function (t) {
      var hasPk = t.fields.some(function (f) { return f.pk; });
      if (!hasPk) warnings.push("Table '" + t.name + "' sans PK");
      if (project.tables.length > 1 && !referenced[t.id]) {
        warnings.push("Table isolée '" + t.name + "'");
      }
    });

    var msg = warnings.length > 0
      ? "Linter : " + warnings.length + " anomalie(s) (" + warnings.slice(0, 3).join(", ") + ")"
      : "Linter : Aucun problème détecté !";

    return { project: null, message: msg };
  }
});
`,
  },

  {
    id: "template.django-models",
    name: "Django Models (Python)",
    version: "1.0.0",
    author: "Communauté AthanorDB",
    category: "export",
    icon: "code",
    tags: ["django", "python", "backend", "models"],
    description: "Génère les classes models.Model Python pour Django avec types et clés étrangères ForeignKey.",
    sourceCode: `athanor.plugin({
  id: "community.django-models",
  name: "Django Models (Python)",
  version: "1.0.0",
  author: "Communauté AthanorDB",
  description: "Exporte votre schéma en classes models.Model Django."
});

function toPascal(str) {
  return String(str || "").replace(/(?:^|_|\\s)([a-z0-9])/g, function (_, l) { return l.toUpperCase(); });
}

function djangoField(f) {
  var t = String(f.type || "").toLowerCase();
  var args = [];
  if (!f.notNull && !f.pk) args.push("null=True, blank=True");
  if (f.unique && !f.pk) args.push("unique=True");
  if (f.default) args.push("default=" + JSON.stringify(f.default));
  var argStr = args.length ? "(" + args.join(", ") + ")" : "()";

  if (f.pk && f.increment) return "models.BigAutoField(primary_key=True)";
  if (f.pk && /uuid/i.test(t)) return "models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)";
  if (/int|serial/.test(t)) return "models.IntegerField" + argStr;
  if (/bool/.test(t)) return "models.BooleanField" + (f.default ? "(default=" + f.default + ")" : "()");
  if (/date-time|timestamp/.test(t)) return "models.DateTimeField" + (args.length ? "(" + args.join(", ") + ")" : "()");
  if (/date/.test(t)) return "models.DateField" + argStr;
  if (/decimal|numeric/.test(t)) return "models.DecimalField(max_digits=10, decimal_places=2)";
  if (/text|clob/.test(t)) return "models.TextField" + argStr;
  return "models.CharField(max_length=255" + (args.length ? ", " + args.join(", ") : "") + ")";
}

athanor.registerExporter({
  id: "django-export",
  label: "Python — Django models.py",
  extension: "py",
  description: "Génère le fichier models.py pour Django.",
  run: function (project) {
    var out = [
      "# models.py generated by AthanorDB",
      "from django.db import models",
      "import uuid\\n"
    ];

    project.tables.forEach(function (t) {
      out.push("class " + toPascal(t.name) + "(models.Model):");
      t.fields.forEach(function (f) {
        out.push("    " + f.name + " = " + djangoField(f));
      });
      out.push("    class Meta:");
      out.push("        db_table = '" + t.name + "'\\n");
    });

    return out.join("\n");
  }
});
`,
  },

  {
    id: "template.sql-importer",
    name: "SQL DDL Importer & Converter",
    version: "1.0.0",
    author: "Communauté AthanorDB",
    category: "import",
    icon: "database",
    tags: ["sql", "ddl", "create table", "importer", "converter", "editor"],
    description:
      "Permet d'utiliser directement du code SQL : importe des fichiers SQL ou convertit du SQL collé dans l'éditeur pour générer les tables et relations visuelles sur le canvas.",
    sourceCode: `athanor.plugin({
  id: "community.sql-importer",
  name: "SQL DDL Importer & Converter",
  version: "1.0.0",
  author: "Communauté AthanorDB",
  description: "Génère les tables et relations visuelles à partir de code SQL (CREATE TABLE, FOREIGN KEY)."
});

function convertSqlToDbml(source) {
  var lines = ["// Généré depuis SQL DDL\\n"];
  var tableRegex = /CREATE\\s+TABLE(?:\\s+IF\\s+NOT\\s+EXISTS)?\\s+["\`']?(?:([a-zA-Z0-9_]+)\\.)?([a-zA-Z0-9_]+)["\`']?\\s*\\(([\\s\\S]*?)\\);/gi;
  var match;
  var tableCount = 0;
  var allFks = [];

  while ((match = tableRegex.exec(source)) !== null) {
    tableCount++;
    var schemaName = match[1];
    var tableName = match[2];
    var body = match[3];

    var fullName = schemaName ? schemaName + "." + tableName : tableName;
    lines.push("Table " + fullName + " {");

    var colLines = body.split(/,(?![^(]*\\))/);

    for (var i = 0; i < colLines.length; i++) {
      var col = colLines[i].trim();
      if (!col) continue;

      // Table-level FOREIGN KEY (col) REFERENCES target (targetCol)
      var fkMatch = /FOREIGN\\s+KEY\\s*\\(["\`']?([a-zA-Z0-9_]+)["\`']?\\)\\s*REFERENCES\\s*["\`']?([a-zA-Z0-9_]+)["\`']?\\s*\\(["\`']?([a-zA-Z0-9_]+)["\`']?\\)/i.exec(col);
      if (fkMatch) {
        allFks.push({ fromTable: fullName, fromCol: fkMatch[1], toTable: fkMatch[2], toCol: fkMatch[3] });
        continue;
      }

      // Table-level PRIMARY KEY (col1, col2)
      if (/^PRIMARY\\s+KEY/i.test(col)) {
        continue;
      }

      // Table-level UNIQUE/CHECK/CONSTRAINT
      if (/^(?:UNIQUE|CHECK|CONSTRAINT)/i.test(col)) {
        continue;
      }

      // Column definition
      var parts = col.split(/\\s+/);
      var colName = parts[0].replace(/["\`']/g, "");
      var colType = parts[1] ? parts[1].replace(/,/g, "") : "varchar";

      var isPk = /PRIMARY\\s+KEY/i.test(col);
      var isAuto = /AUTO_INCREMENT|AUTOINCREMENT|SERIAL/i.test(col);
      var isNotNull = /NOT\\s+NULL/i.test(col);
      var isUnique = /UNIQUE/i.test(col);
      var defMatch = /DEFAULT\\s+([^,\\s]+)/i.exec(col);

      // Inline REFERENCES target(col)
      var inlineFk = /REFERENCES\\s+["\`']?([a-zA-Z0-9_]+)["\`']?\\s*\\(["\`']?([a-zA-Z0-9_]+)["\`']?\\)/i.exec(col);
      if (inlineFk) {
        allFks.push({ fromTable: fullName, fromCol: colName, toTable: inlineFk[1], toCol: inlineFk[2] });
      }

      var settings = [];
      if (isPk) settings.push("pk");
      if (isAuto) settings.push("increment");
      if (isNotNull && !isPk) settings.push("not null");
      if (isUnique && !isPk) settings.push("unique");
      if (defMatch) settings.push("default: " + defMatch[1]);

      var settingsStr = settings.length > 0 ? " [" + settings.join(", ") + "]" : "";
      lines.push("  " + colName + " " + colType + settingsStr);
    }

    lines.push("}\\n");
  }

  for (var k = 0; k < allFks.length; k++) {
    var fk = allFks[k];
    lines.push("Ref: " + fk.fromTable + "." + fk.fromCol + " > " + fk.toTable + "." + fk.toCol);
  }

  if (tableCount === 0) {
    throw new Error("Aucune instruction CREATE TABLE valide trouvée dans le code SQL.");
  }

  return lines.join("\\n");
}

// 1. Importer : disponible dans le dialogue d'Importation
athanor.registerImporter({
  id: "sql-ddl",
  label: "SQL — DDL (CREATE TABLE)",
  fileExtensions: ["sql", "ddl"],
  description: "Parse du code SQL pour générer automatiquement les tables et relations visuelles sur le canvas.",
  run: function (source) {
    return { dbml: convertSqlToDbml(source) };
  }
});

// 2. Commande Éditeur : convertir du SQL collé directement dans l'éditeur
athanor.registerEditorCommand({
  id: "convert-sql-to-dbml",
  label: "Convertir le code SQL en DBML",
  shortcut: "Ctrl+Alt+S",
  description: "Transforme du code SQL en DBML pour actualiser instantanément le schéma visuel.",
  run: function (input) {
    var raw = input.selectedText || input.text;
    var converted = convertSqlToDbml(raw);
    return {
      text: input.selectedText ? input.text.replace(input.selectedText, converted) : converted,
      message: "SQL converti en DBML avec succès !"
    };
  }
});
`,
  },
];

// ---------------------------------------------------------------------------
// Boilerplates for the Plugin Creator Studio
// ---------------------------------------------------------------------------

export const PLUGIN_BOILERPLATES = [
  {
    id: "boilerplate-exporter",
    label: "Modèle : Exporteur de code personnalisé (Go, Rust, etc.)",
    code: `athanor.plugin({
  id: "me.custom-exporter",
  name: "Mon Exporteur Personnalisé",
  version: "1.0.0",
  author: "Mon Nom",
  description: "Exporte les tables vers un format de code personnalisé.",
  settings: [
    { key: "includeHeader", label: "Inclure l'en-tête de fichier", type: "boolean", default: true }
  ]
});

athanor.registerExporter({
  id: "custom-format",
  label: "Mon Format (.txt)",
  extension: "txt",
  description: "Description de mon format d'exportation.",
  run: function (project, context) {
    var lines = [];
    if (context.settings.includeHeader) {
      lines.push("// Généré pour le projet : " + project.name);
    }

    project.tables.forEach(function (table) {
      lines.push("TABLE: " + table.name);
      table.fields.forEach(function (field) {
        lines.push("  - " + field.name + " (" + field.type + ")");
      });
      lines.push("");
    });

    return lines.join("\\n");
  }
});
`,
  },
  {
    id: "boilerplate-canvas-command",
    label: "Modèle : Commande Canvas (Transformation du schéma)",
    code: `athanor.plugin({
  id: "me.custom-canvas-tool",
  name: "Mon Outil Canvas",
  version: "1.0.0",
  author: "Mon Nom",
  description: "Applique des transformations automatiques sur les tables du canvas."
});

athanor.registerCanvasCommand({
  id: "prefix-tables",
  label: "Ajouter le préfixe tbl_ aux tables",
  description: "Ajoute tbl_ à toutes les tables sélectionnées.",
  shortcut: "Ctrl+Alt+P",
  run: function (project, context) {
    var selected = (context.selection && context.selection.tableIds) || [];
    var scoped = selected.length > 0;

    var tables = project.tables.map(function (table) {
      if (scoped && selected.indexOf(table.id) === -1) return table;
      if (table.name.indexOf("tbl_") === 0) return table;
      return Object.assign({}, table, { name: "tbl_" + table.name });
    });

    return {
      project: Object.assign({}, project, { tables: tables }),
      message: "Préfixe tbl_ ajouté avec succès !"
    };
  }
});
`,
  },
  {
    id: "boilerplate-editor-command",
    label: "Modèle : Commande Éditeur DBML",
    code: `athanor.plugin({
  id: "me.custom-editor-tool",
  name: "Mon Outil Éditeur DBML",
  version: "1.0.0",
  author: "Mon Nom",
  description: "Modifie le texte source dans l'éditeur de code DBML."
});

athanor.registerEditorCommand({
  id: "insert-timestamp-comment",
  label: "Insérer l'en-tête de date",
  description: "Ajoute un commentaire avec la date du jour en haut du document.",
  run: function (input) {
    var header = "// Schéma mis à jour le " + new Date().toLocaleDateString() + "\\n\\n";
    return {
      text: header + input.text,
      message: "En-tête de date inséré"
    };
  }
});
`,
  },
  {
    id: "boilerplate-importer",
    label: "Modèle : Importateur personnalisé (ex: format CSV / YAML)",
    code: `athanor.plugin({
  id: "me.custom-importer",
  name: "Mon Importateur",
  version: "1.0.0",
  author: "Mon Nom",
  description: "Convertit un format personnalisé en DBML pour le projet."
});

athanor.registerImporter({
  id: "custom-import",
  label: "Format Texte Simple",
  fileExtensions: ["txt"],
  description: "Convertit des lignes 'table_name: col1, col2' en DBML.",
  run: function (input) {
    var lines = String(input || "").split("\\n");
    var dbml = [];

    lines.forEach(function (line) {
      var parts = line.split(":");
      if (parts.length >= 2) {
        var tableName = parts[0].trim();
        var cols = parts[1].split(",");
        dbml.push("Table " + tableName + " {");
        dbml.push("  id int [pk, increment]");
        cols.forEach(function (col) {
          var cName = col.trim();
          if (cName) dbml.push("  " + cName + " varchar");
        });
        dbml.push("}\\n");
      }
    });

    return { dbml: dbml.join("\\n") };
  }
});
`,
  },
];
