CREATE TABLE "criteria" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "is_usable_prioritization" varchar(255),
  "id_type" integer,
  "id_nature" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "criteria_hyperparameter_qualitative" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_criteria_source" integer,
  "id_criteria_target" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "criteria_hyperparameter_quantitative" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "description" varchar(255),
  "id_group_criteria_target" integer,
  "id_group_criteria_source" integer,
  "id_model" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "criteria_nature" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "criteria_theme_list" (
  "id_theme" integer NOT NULL,
  "id_criteria" integer NOT NULL,
  PRIMARY KEY ("id_theme", "id_criteria")
);

CREATE TABLE "criteria_translation" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255),
  "description" varchar(255),
  "short_label" varchar(255),
  "id_language" integer,
  "id_criteria" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "criteria_type" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(150),
  PRIMARY KEY ("id")
);

CREATE TABLE "DbtQueryLog" (
  "log_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "model_name" varchar(255) NOT NULL,
  "session_id" integer,
  "request_id" integer,
  "database_name" varchar(128),
  "start_time" timestamp,
  "end_time" timestamp,
  "duration_sec" numeric(18,6),
  "duration_ms" numeric(18,3),
  "cpu_sec" numeric(18,6),
  "cpu_ms" numeric(18,3),
  "wait_sec" numeric(18,6),
  "wait_ms" numeric(18,3),
  "requested_memory_MB" numeric(18,2),
  "granted_memory_MB" numeric(18,2),
  "used_memory_MB" numeric(18,2),
  "max_used_memory_MB" numeric(18,2),
  "requested_memory_GB" numeric(18,4),
  "granted_memory_GB" numeric(18,4),
  "used_memory_GB" numeric(18,4),
  "max_used_memory_GB" numeric(18,4),
  "degree_of_parallelism" integer,
  "wait_type" varchar(60),
  "blocking_session_id" integer,
  "tempdb_user_MB" numeric(18,2),
  "tempdb_internal_MB" numeric(18,2),
  "logical_reads" bigint,
  "writes" bigint,
  "row_count" bigint,
  "query_status" varchar(50),
  "command_type" varchar(50),
  "query_text" text,
  "created_date" timestamp,
  PRIMARY KEY ("log_id")
);

CREATE TABLE "group_criteria" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "group_criteria_list" (
  "id_group_criteria" integer NOT NULL,
  "id_criteria" integer NOT NULL,
  PRIMARY KEY ("id_group_criteria", "id_criteria")
);

CREATE TABLE "hyperparameter" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "class_name" varchar(150),
  PRIMARY KEY ("id")
);

CREATE TABLE "hyperparameter_qualitative_list" (
  "id_hyperparameter" integer NOT NULL,
  "id_criteria_hyperparameter_qualitative" integer NOT NULL,
  "inferior_threshold" numeric(18,6),
  "superior_threshold" numeric(18,6),
  PRIMARY KEY ("id_hyperparameter", "id_criteria_hyperparameter_qualitative")
);

CREATE TABLE "hyperparameter_quantitative" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "hyperparameter_quantitative_list" (
  "id_hyperparameter_quantitative" integer NOT NULL,
  "id_criteria_hyperparameter_quantitative" integer NOT NULL,
  "value_dec" numeric(18,0),
  "value_varchar" varchar(255),
  PRIMARY KEY ("id_hyperparameter_quantitative", "id_criteria_hyperparameter_quantitative")
);

CREATE TABLE "model" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(150),
  "number_input_criteria" integer,
  "number_output_criteria" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "PAR01" (
  "month" varchar(3),
  "active" integer,
  "creator" varchar(150),
  "tracker_id" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR02" (
  "month" varchar(3),
  "active" integer,
  "id_trackers_package" integer,
  "tracker_id" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR03" (
  "creator" varchar(150),
  "description" text,
  "dimension_id" integer,
  "id_trackers_package" integer,
  "parameter" varchar(150),
  "tag" varchar(150),
  "threshold_value" varchar(150),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR04" (
  "group_id" bigint,
  "perimeter_id" bigint,
  "year" bigint,
  "month" text
);

CREATE TABLE "PAR05" (
  "creator" varchar(150),
  "default_indicator" integer,
  "description" text,
  "dimension_id" integer,
  "parameter" varchar(150),
  "ref_perimeter_id" integer,
  "scenario_id" integer,
  "tag" varchar(150),
  "threshold_set_id" integer,
  "threshold_type" varchar(150),
  "threshold_value" varchar(150),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR06" (
  "filter_value" varchar(150),
  "id_filter" integer,
  "indicator_id" integer,
  "operator" varchar(150),
  "rule_id" integer,
  "scenario_id" integer,
  "tracker_id" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR06_bis" (
  "filter_value" varchar(150),
  "id_filter" integer,
  "indicator_id" integer,
  "operator" varchar(150),
  "rule_id" integer,
  "scenario_id" integer,
  "tracker_id" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR07" (
  "id_criteria" integer,
  "id_function" integer,
  "id_params" integer,
  "indicator_id" integer,
  "priorisation_id" integer,
  "scenario_id" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR08" (
  "creator" varchar(150),
  "description" text,
  "historic_priorisation_id" integer,
  "id_algo" integer,
  "priorisation_id" integer,
  "statut" integer,
  "tag" varchar(150),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR09" (
  "id" integer,
  "is_active" integer,
  "type" varchar(150),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR10" (
  "group_id" bigint,
  "criteria_name" text,
  "training_id" bigint
);

CREATE TABLE "PAR11" (
  "comparable_perimeter" integer,
  "id_trackers_package" integer,
  "pod" integer,
  "priorisation_id" integer,
  "study" integer,
  "zone_id" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR12" (
  "month" text,
  "year" bigint,
  "training_id" bigint,
  "perimeter_id" bigint
);

CREATE TABLE "PAR13" (
  "depth" varchar(150),
  "id_config" integer,
  "ponderation" numeric(20,5),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR14" (
  "creator" varchar(150),
  "id_params" integer,
  "pos" integer,
  "value" numeric(20,5),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR15" (
  "creator" varchar(150),
  "id_algo" integer,
  "id_function" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR16" (
  "perimeter_id" integer,
  "col_code" varchar(150),
  "config_id" integer,
  "default_indicator" integer,
  "hierarchy_table_name" varchar(150),
  "item_table_name" varchar(150),
  "model_outlier" integer,
  "threshold_outliers" varchar(150),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR18" (
  "id_target" integer,
  "target" varchar(153),
  "tracker_or_model" varchar(150),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR19" (
  "critical_threshold" numeric(20,5),
  "id_kci" integer,
  "target_id" integer,
  "warning_threshold" numeric(20,5),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR20" (
  "model_outlier" integer,
  "perimeter_train" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR21" (
  "perimeter_id" integer,
  "default_indicator" integer,
  "dimension_id" integer,
  "par_value" varchar(150),
  "parameter" varchar(150),
  "scenario_id" integer,
  "script" varchar(150),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR22" (
  "source_tracker" integer,
  "tracker_id" integer
);

CREATE TABLE "PAR23" (
  "criteria" varchar(150),
  "description" text,
  "id_model" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR27" (
  "active" integer,
  "main_perimeter_id" integer,
  "priorisation_active" integer,
  "tracker_id" integer,
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR28" (
  "calibration_id" integer,
  "mat_value" numeric(20,5),
  "max_perf" numeric(20,5),
  "min_perf" numeric(20,5),
  "seuil_1" numeric(20,5),
  "seuil_2" numeric(20,5),
  "seuil_acc" numeric(20,5),
  "seuil_cr" numeric(20,5),
  "seuil_grav" numeric(20,5),
  "seuil_mat" numeric(20,5),
  "seuil_season" numeric(20,5),
  "last_updated_date" timestamp NOT NULL
);

CREATE TABLE "PAR29" (
  "hyperparameters_id" bigint,
  "class" text,
  "threshold_inf" double precision,
  "threshold_up" double precision,
  "creator" text,
  "last_updated_date" date
);

CREATE TABLE "PAR30" (
  "hyperparameters_id" bigint,
  "training_id" bigint,
  "class" text,
  "threshold_inf" double precision,
  "threshold_up" double precision
);

CREATE TABLE "PAR31" (
  "id" integer NOT NULL,
  "critere" varchar(200) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "PAR32" (
  "id_group" integer NOT NULL,
  "id_critere" integer NOT NULL,
  PRIMARY KEY ("id_group", "id_critere")
);

CREATE TABLE "PAR33" (
  "id_new_crit" integer NOT NULL,
  "id_used_crits" integer,
  "description" varchar(400),
  PRIMARY KEY ("id_new_crit")
);

CREATE TABLE "parameter_qualitative_list" (
  "id_hyperparameter" integer NOT NULL,
  "id_criteria_hyperparameter_qualitative" integer NOT NULL,
  "id_training" integer,
  "inferior_threshold" numeric(18,6),
  "superior_threshold" numeric(18,6)
);

CREATE TABLE "parameter_quantitative_list" (
  "id_hyperparameter_quantitative" integer NOT NULL,
  "id_criteria_hyperparameter_quantitative" integer NOT NULL,
  "id_training" integer NOT NULL,
  "value_dec" numeric(18,0),
  "value_varchar" varchar(255),
  PRIMARY KEY ("id_hyperparameter_quantitative", "id_criteria_hyperparameter_quantitative", "id_training")
);

CREATE TABLE "period_perimeter" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "year" integer,
  "id_period" integer NOT NULL,
  "id_perimeter" integer,
  "month" varchar(3),
  PRIMARY KEY ("id")
);

CREATE TABLE "theme_criteria" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "training" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(150),
  PRIMARY KEY ("id")
);

CREATE TABLE "training_application_list" (
  "id_training" integer NOT NULL,
  "id_period_perimeter_apply" integer NOT NULL,
  PRIMARY KEY ("id_training", "id_period_perimeter_apply")
);

CREATE TABLE "training_train_list" (
  "id_period_perimeter_train" integer NOT NULL,
  "id_training" integer NOT NULL,
  PRIMARY KEY ("id_period_perimeter_train", "id_training")
);
